//! Dynamixel PH42 PH54 PM42 PM54 model definitions.

use crate::model;

model![PH42, PH54, PM42, PM54 => {
    ModelNumber: 0, 2, Access::R, Area::Eeprom, None,
    ModelInformation: 2, 4, Access::R, Area::Eeprom, None,
    FirmwareVersion: 6, 1, Access::R, Area::Eeprom, None,
    Id: 7, 1, Access::Rw, Area::Eeprom, None,
    BaudRate: 8, 1, Access::Rw, Area::Eeprom, None,
    DriveMode: 10, 1, Access::Rw, Area::Eeprom, None,
    OperatingMode: 11, 1, Access::Rw, Area::Eeprom, None,
    HomingOffset: 20, 4, Access::Rw, Area::Eeprom, Some(UnitScale::new(Unit::Pulse, 1f32)),
    MovingThreshold: 24, 4, Access::Rw, Area::Eeprom, Some(UnitScale::new(Unit::RevPerMinute, 0.01f32)),
    TemperatureLimit: 31, 1, Access::Rw, Area::Eeprom, Some(UnitScale::new(Unit::DegreesCelsius, 1f32)),
    MaxVoltageLimit: 32, 2, Access::Rw, Area::Eeprom, Some(UnitScale::new(Unit::Volt, 0.1f32)),
    MinVoltageLimit: 34, 2, Access::Rw, Area::Eeprom, Some(UnitScale::new(Unit::Volt, 0.1f32)),
    PwmLimit: 36, 2, Access::Rw, Area::Eeprom, Some(UnitScale::new(Unit::Percent, 0.0498f32)),
    CurrentLimit: 38, 2, Access::Rw, Area::Eeprom, Some(UnitScale::new(Unit::Ampere, 0.001f32)),
    AccelerationLimit: 40, 4, Access::Rw, Area::Eeprom, Some(UnitScale::new(Unit::RevPerMinuteSquared, 1f32)),
    VelocityLimit: 44, 4, Access::Rw, Area::Eeprom, Some(UnitScale::new(Unit::RevPerMinute, 0.01f32)),
    MaxPositionLimit: 48, 4, Access::Rw, Area::Eeprom, Some(UnitScale::new(Unit::Pulse, 1f32)),
    MinPositionLimit: 52, 4, Access::Rw, Area::Eeprom, Some(UnitScale::new(Unit::Pulse, 1f32)),
    StartupConfiguration: 60, 1, Access::Rw, Area::Eeprom, None,
    Shutdown: 63, 1, Access::Rw, Area::Eeprom, None,
    TorqueEnable: 512, 1, Access::Rw, Area::Ram, None,
    HardwareErrorStatus: 518, 1, Access::R, Area::Ram, None,
    VelocityIGain: 524, 2, Access::Rw, Area::Ram, None,
    VelocityPGain: 526, 2, Access::Rw, Area::Ram, None,
    PositionPGain: 532, 2, Access::Rw, Area::Ram, None,
    BusWatchdog: 546, 1, Access::Rw, Area::Ram, Some(UnitScale::new(Unit::Second, 0.02f32)),
    GoalPwm: 548, 2, Access::Rw, Area::Ram, Some(UnitScale::new(Unit::Percent, 0.0498f32)),
    GoalCurrent: 550, 2, Access::Rw, Area::Ram, Some(UnitScale::new(Unit::Ampere, 0.001f32)),
    GoalVelocity: 552, 4, Access::Rw, Area::Ram, Some(UnitScale::new(Unit::RevPerMinute, 0.01f32)),
    ProfileAcceleration: 556, 4, Access::Rw, Area::Ram, Some(UnitScale::new(Unit::RevPerMinuteSquared, 1f32)),
    ProfileVelocity: 560, 4, Access::Rw, Area::Ram, Some(UnitScale::new(Unit::RevPerMinute, 0.01f32)),
    GoalPosition: 564, 4, Access::Rw, Area::Ram, Some(UnitScale::new(Unit::Pulse, 1f32)),
    Moving: 570, 1, Access::R, Area::Ram, None,
    MovingStatus: 571, 1, Access::R, Area::Ram, None,
    PresentPwm: 572, 2, Access::R, Area::Ram, Some(UnitScale::new(Unit::Percent, 0.0498f32)),
    PresentCurrent: 574, 2, Access::R, Area::Ram, Some(UnitScale::new(Unit::Ampere, 0.001f32)),
    PresentVelocity: 576, 4, Access::R, Area::Ram, Some(UnitScale::new(Unit::RevPerMinute, 0.01f32)),
    PresentPosition: 580, 4, Access::R, Area::Ram, Some(UnitScale::new(Unit::Pulse, 1f32)),
    VelocityTrajectory: 584, 4, Access::R, Area::Ram, Some(UnitScale::new(Unit::RevPerMinute, 0.01f32)),
    PositionTrajectory: 588, 4, Access::R, Area::Ram, Some(UnitScale::new(Unit::Pulse, 1f32)),
    PresentInputVoltage: 592, 2, Access::R, Area::Ram, Some(UnitScale::new(Unit::Volt, 0.1f32)),
    PresentTemperature: 594, 1, Access::R, Area::Ram, Some(UnitScale::new(Unit::DegreesCelsius, 1f32)),
    PositionDGain: 528, 2, Access::Rw, Area::Ram, None,
    PositionIGain: 530, 2, Access::Rw, Area::Ram, None,
    ProtocolType: 13, 1, Access::Rw, Area::Eeprom, None,
    ExternalPortMode1: 56, 1, Access::Rw, Area::Eeprom, None,
    ExternalPortMode2: 57, 1, Access::Rw, Area::Eeprom, None,
    ExternalPortMode3: 58, 1, Access::Rw, Area::Eeprom, None,
    ExternalPortMode4: 59, 1, Access::Rw, Area::Eeprom, None,
    LedRed: 513, 1, Access::Rw, Area::Ram, None,
    LedGreen: 514, 1, Access::Rw, Area::Ram, None,
    LedBlue: 515, 1, Access::Rw, Area::Ram, None,
    Feedforward2NdGain: 536, 2, Access::Rw, Area::Ram, None,
    Feedforward1StGain: 538, 2, Access::Rw, Area::Ram, None,
    RealtimeTick: 568, 2, Access::R, Area::Ram, Some(UnitScale::new(Unit::Second, 0.001f32)),
    ExternalPortData1: 600, 2, Access::Rw, Area::Ram, None,
    ExternalPortData2: 602, 2, Access::Rw, Area::Ram, None,
    ExternalPortData3: 604, 2, Access::Rw, Area::Ram, None,
    ExternalPortData4: 606, 2, Access::Rw, Area::Ram, None,
}];
